### ISSUE TITLE
多选材质调整任意参数导致材质 Keyword 值被修改, Disabled Shader Passes 被修改.

### ISSUE THREAD

**Issue by pengjiaxusz** [JasonMa0012/LWGUI#73]
## 遇到的问题
多选材质调整任意参数导致材质 Keyword 值被修改, Disabled Shader Passes 被修改.
## 版本信息
**Unity版本: 6000.0.32f1**

**渲染管线: URP 17.0.3**

 **LWGUI 版本: https://github.com/JasonMa0012/LWGUI/commit/bcc01b0bb4a29ed702761ca7d017db5f86c33dfe**
## 复现所用资源 .unitypackage 下载
[LWGUI_Multiselect.zip](https://github.com/user-attachments/files/18345445/LWGUI_Multiselect.zip)(文件大小7kb, 需解压)
![image](https://github.com/user-attachments/assets/717a58c1-b865-4192-ac8f-d5cf76b37cdf)

## 复现步骤

1. 场景中存在3个方块, 从左到右依次为:
![image](https://github.com/user-attachments/assets/6f9565db-fb0f-4fbd-a703-61c6c3b81c8d)
方块1, 启用关键字 `_GREEN_ON`
![image](https://github.com/user-attachments/assets/e123f79d-caf4-4f3f-b783-69ef9151fe85)
方块2, 禁用关键字 `_GREEN_ON`
![image](https://github.com/user-attachments/assets/0cca0e5b-1878-457c-9a44-d8948ab3d37e)
方块3, 禁用关键字 `_GREEN_ON`, 禁用 Pass `UniversalForward` (使用 Preset 中的禁用启用Pass功能实现)
![image](https://github.com/user-attachments/assets/6c79085b-9ccc-4b6c-a676-a11f93953ed0)
2. 选中3个物体的材质
![image](https://github.com/user-attachments/assets/fffe240b-62f0-416d-b90b-17635f261847)
3. 修改 `多选3个材质后调整此值` 的值
![image](https://github.com/user-attachments/assets/39b11e2d-3c0d-4413-80dd-93afc2d77170)
会看到所有方块全变绿了
![image](https://github.com/user-attachments/assets/94f6ce3e-7a99-48c2-8ab4-f7560a8f6fd1)
在 `Inspector` 的 `Debug` 中看到关键字与 Disabled Shader Passes 被修改, 但是 LWGUI 显示是正常的. 以 PassOff 材质为例:
**Debug 面板** 启用 `GREEN_ON`, 无禁用 Pass
![image](https://github.com/user-attachments/assets/fdeefdd5-fad6-4934-961a-49a72e0c3b37)
**Normal 面板** 禁用 `GREEN_ON`, 有禁用 `UniversalForward` Pass
![image](https://github.com/user-attachments/assets/b5c7a98e-625a-46b4-b863-46f8e4b3a627)
4. 按下 `Ctrl + S` 保存后又会恢复正常
![image](https://github.com/user-attachments/assets/76c243aa-251d-490a-9d81-9e1eea5093dc)
## 相关代码
_MultiselectTest.shader
```HLSL

Shader "LWGUI/MultiselectTest"
{
	Properties
	{
		[Preset(DisablePass)] _Preset_DisablePass("DisablePass", Float) = 0
		[Main(Green On, _GREEN_ON, off, on)] _Group_GreenOn("Green On", Float) = 0
		_OtherValue("多选3个材质后调整此值%3个材质分别启用禁用了 GreenOn 与 UniversalForward Pass%", Float) = 0
	}
	SubShader
	{
		Pass
		{
			Tags
			{
				"LightMode" = "UniversalForward"
			}
			HLSLPROGRAM
			#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
			#pragma shader_feature_local _GREEN_ON
			#pragma vertex VS
			#pragma fragment FS
			struct Varyings
			{
				float4 positionCS : SV_POSITION;
			};

			Varyings VS(float3 positionOS : POSITION)
			{
				Varyings o = (Varyings)0;
				VertexPositionInputs vertex = GetVertexPositionInputs(positionOS);
				o.positionCS = vertex.positionCS;
				return o;
			}

			float4 FS(Varyings i) : SV_Target
			{
				float3 finalColor = float3(0, 0, 0);
				#if _GREEN_ON
				    finalColor = float3(0, 1, 0);
				#endif

				return float4(finalColor, 1);
			}
			ENDHLSL
		}
	}
    CustomEditor "LWGUI.LWGUI"
}
```
## 相关 Preset
DisablePass
![image](https://github.com/user-attachments/assets/0710bfcf-86db-4f55-9695-966f6c7ac3b3)
DisablePass.asset
```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &11400000
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 28fbcbca3fb14507af6ed5c104c40b84, type: 3}
  m_Name: DisablePass
  m_EditorClassIdentifier: 
  presets:
  - presetName: Enable UniversalForward
    propertyValues: []
    enabledKeywords: []
    disabledKeywords: []
    enabledPasses:
    - UniversalForward
    disabledPasses: []
    renderQueue: -1
  - presetName: Disable UniversalForward
    propertyValues: []
    enabledKeywords: []
    disabledKeywords: []
    enabledPasses: []
    disabledPasses:
    - UniversalForward
    renderQueue: -1

```
